### ISSUE TITLE
Fail NavMeshQuery after loading all_tiles_tilecache.bin

### ISSUE THREAD

**Issue by evgeny-detkov** [ppiastucki/recast4j#10]
I exported the bin-file from [recastnavigation](https://github.com/recastnavigation/recastnavigation) (C ++), I use [TileCacheReader](https://github.com/ppiastucki/recast4j/blob/master/detourtilecache/src/main/java/org/recast4j/detour/tilecache/io/TileCacheReader.java) to load the bin in the java-version, navmesh is loaded, but incorrectly, in a different way, unlike the C ++ example of RecastDemo.
I exported in java obj to bin using [TileCacheWriter](https://github.com/ppiastucki/recast4j/blob/master/detourtilecache/src/main/java/org/recast4j/detour/tilecache/io/TileCacheWriter.java). 

		boolean cCompatibility = true;
		InputGeom geom = new ObjImporter().load(RecastBuilder.class.getResourceAsStream("nav_test.obj"));
		TestTileLayerBuilder layerBuilder = new TestTileLayerBuilder(geom);
		List<byte[]> layers = layerBuilder.build(ByteOrder.LITTLE_ENDIAN, cCompatibility, 1);
		TileCache tc = getTileCache(geom, ByteOrder.LITTLE_ENDIAN, cCompatibility);
		for (byte[] data : layers) {
			long ref = tc.addTile(data, 0);
			tc.buildNavMeshTile(ref);
		}
		
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		writer.write(baos, tc, ByteOrder.LITTLE_ENDIAN, cCompatibility);
		
		try(OutputStream outputStream = new FileOutputStream("_temp.bin")) {
			baos.writeTo(outputStream);
		}

Then again I load bin TileCacheReader, the same problems. NavMeshQuery is incorrectly formed, I can not correctly get information on polygons.
Can you check the problem?

**Comment by ppiastucki** [comment]
Would you please attach the file you exported from RecastDemo? 

There is a related test that demonstrates how to import bin files containing tile cache data - https://github.com/ppiastucki/recast4j/blob/master/detourtilecache/src/test/java/org/recast4j/detour/tilecache/io/TileCacheReaderTest.java
and it actually loads the following 2 files created with C++ version of RecastDemo:
https://github.com/ppiastucki/recast4j/tree/master/detourtilecache/src/test/resources

**Comment by evgeny-detkov** [comment]
I'm using for test [this bin file](https://github.com/ppiastucki/recast4j/blob/master/detourtilecache/src/test/resources/dungeon_all_tiles_tilecache.bin) or its my export bin-file from RecastDemo
[all_tiles_tilecache.zip](https://github.com/ppiastucki/recast4j/files/1092781/all_tiles_tilecache.zip)

I created Main.java, in it I use object of class TiledFindPathTest.java.
TiledFindPathTest.java I modified it a bit, added open bin-file from TileCacheReaderTest.java
[TiledFindPathTest.zip](https://github.com/ppiastucki/recast4j/files/1092716/TiledFindPathTest.zip)

The file opens, but later an error appears in the calculations.

	Exception in thread "main" java.lang.IllegalArgumentException: Start or end ref = 0
	at org.recast4j.detour.NavMeshQuery.findPath(NavMeshQuery.java:725)
	at org.recast4j.detour.TiledFindPathTest.testFindPath(TiledFindPathTest.java:60)
	at Main.main(Main.java:14)

It turns out that the function query.findNearestPoly (start, extents, filter) returns null.

If you uncomment the 31 lines (dynamic build navmesh for dungeon.obj)

	//this.navmesh = new TestTiledNavMeshBuilder (). GetNavMesh ();

then navmesh correctly loaded and calculated the path from the point start to end.
Am I doing something wrong? What else can I check?

**Comment by ppiastucki** [comment]
Thanks for the information. I will look into the issue. 
Meanwhile, you might try using tiles nav mesh sets rather than tile cache. 
Please see https://github.com/ppiastucki/recast4j/blob/master/detour/src/test/java/org/recast4j/detour/io/MeshSetReaderTest.java for the respective example on how to load tiled nav meshes (all_tiles_navmesh.bin in this case).

**Comment by evgeny-detkov** [comment]
Ok, thanks, I'll try.
But then I still need to load tileCache to use the dynamic obstacles functionality (addObstacle).

**Comment by evgeny-detkov** [comment]
After using dungeon_all_tiles_navmesh.bin, everything works great! Path is found.
Now to understand what's wrong with tileCache ...

**Comment by ppiastucki** [comment]
The issue is hopefully fixed now, please see https://github.com/ppiastucki/recast4j/blob/master/detourtilecache/src/test/java/org/recast4j/detour/tilecache/TileCacheFindPathTest.java.

**Comment by evgeny-detkov** [comment]
Everything works great! Obstacles also work, thank you very much!
