### ISSUE TITLE
Request for info

### ISSUE THREAD

**Issue by Warkdev** [ppiastucki/recast4j#11]
Hello,
I would like to use this lib to create some navmesh that could be used by the detour module afterwards. However, I find very little info about the input file structure I should give to recast to generate the navmesh. Is there somewhere the info on what are the steps and the structure of the files ?
Thank you,
Warkdev

**Comment by evgeny-detkov** [comment]
I used https://github.com/recastnavigation/recastnavigation to create a bin file based on my own model.
You need to build an exe utility using the SDL2 library. Compile RecastDemo.exe.
1) Launch RecastDemo
2) "Choose sample" -> Temp Obstacle
3) "Choose mesh" -> you mesh from folder RecastDemo / Bin / Meshes, for example, nav_test.obj
4) The "Build" -> button will merge
5) "Save" button
![recastdemo_screen](https://user-images.githubusercontent.com/5319984/27451373-78a0155e-5797-11e7-8728-342def747958.JPG)

**Comment by Warkdev** [comment]
Hello, thank you for your answer. I've built RecastDemo too but I really want to extract terrain data from an existing game and create my own input files for Recast to create Navmesh. However, this is not clear to me how the input files look like and the documentation available is... lacking.

**Comment by ppiastucki** [comment]
There is no such thing as official input format. You simply need to feed Recast with triangles  (polygon soup). The expected input is simply an array of triangles (indices) and vertices (coordinates), see 
https://github.com/ppiastucki/recast4j/blob/master/recast/src/test/java/org/recast4j/recast/RecastSoloMeshTest.java#L93-L94
The way you get the arrays is up to you. The test include a minimalistic .obj file loader (https://github.com/ppiastucki/recast4j/blob/master/recast/src/test/java/org/recast4j/recast/ObjImporter.java), but you can use any other format (dae, fbx) as long as you can transform it into triangles or even generate the triangles procedurally.

**Comment by Warkdev** [comment]
Thank you ppiastucki :)
Very useful work !
Tal'
