### ISSUE TITLE
Tilecache add obstacle error

### ISSUE THREAD

**Issue by cchenqiang** [ppiastucki/recast4j#113]
![image](https://user-images.githubusercontent.com/16534217/119636424-32d97680-be47-11eb-91da-9305243e27de.png)
I use tilecache to add a lot of obstacles, but this error will appear, and then tilecache can't add or remove obstacles again. I hope you can answer my questions.thank you!

**Comment by ppiastucki** [comment]
Hi,
Would you be able to provide a test case which can be used to reproduce the problem?

**Comment by cchenqiang** [comment]
> 嗨，
> 您能否提供一个可用于重现问题的测试用例？

[demo.zip](https://github.com/ppiastucki/recast4j/files/6550887/demo.zip)
Here are my map files and test cases. Thank you for answering for me!

**Comment by cchenqiang** [comment]
> Hi,
> Would you be able to provide a test case which can be used to reproduce the problem?


[java.zip](https://github.com/ppiastucki/recast4j/files/6551410/java.zip)
This is my test case, thank you for answering!
