### ISSUE TITLE
Tilecache add obstacle error

### ISSUE THREAD

**Issue by cchenqiang** [ppiastucki/recast4j#115]
Hello, I tried to add an area attribute to tilecacheobject in tilecache, and then I reported an error. This is my test case.
Exception in thread "main" java.lang.RuntimeException: Buffer too small
	at org.recast4j.detour.tilecache.TileCacheBuilder.buildTileCacheRegions(TileCacheBuilder.java:162)
	at org.recast4j.detour.tilecache.TileCache.buildNavMeshTile(TileCache.java:523)
	at org.recast4j.detour.tilecache.TileCache.update(TileCache.java:456)
	at TestAddObstacle.testAddObstacle(TestAddObstacle.java:133)
	at TestAddObstacle.main(TestAddObstacle.java:105)

[java.zip](https://github.com/ppiastucki/recast4j/files/6558298/java.zip)
This test case needs to modify the source code.
Please answer for me. Thank you!

**Comment by ppiastucki** [comment]
The obstacles you create in your test case are huge. It looks like an incorrect method is used, please try:
```
 public long addBoxObstacle(float[] bmin, float[] bmax) {
```
instead of:
```
    public long addBoxObstacle(float[] center, float[] extents, float yRadians) {
```

**Comment by cchenqiang** [comment]
我修改了源码,实际上是
`public long addBoxObstacle(float[] center, float[] extents, int area) {`

` public class TileCacheObstacle {

    public enum TileCacheObstacleType {
        CYLINDER, BOX, ORIENTED_BOX
    };

    final int index;
    TileCacheObstacleType type;
    final float[] pos = new float[3];
    final float[] bmin = new float[3];
    final float[] bmax = new float[3];
    float radius, height;
    final float[] center = new float[3];
    final float[] extents = new float[3];
    final float[] rotAux = new float[2]; // { cos(0.5f*angle)*sin(-0.5f*angle); cos(0.5f*angle)*cos(0.5f*angle) - 0.5 }
    List<Long> touched = new ArrayList<>();
    final List<Long> pending = new ArrayList<>();
    int salt;
    ObstacleState state = ObstacleState.DT_OBSTACLE_EMPTY;
    TileCacheObstacle next;
    public int area;
    public TileCacheObstacle(int index) {
        salt = 1;
        this.index = index;
    }

}`

` builder.markBoxArea(layer, tile.header.bmin, m_params.cs, m_params.ch, ob.bmin, ob.bmax, ob.area);`

**Comment by ppiastucki** [comment]
I do not fully understand the last comment. By default, the following method:
``` 
public long addBoxObstacle(float[] center, float[] extents, float yRadians) {
```
expects the center and the extent rather than the actual coordinates of the bounding box. 
I am not sure why you had to modify it and how it was changed.
Please keep in mind that tile cache can be used to add obstacles that block passages only, they cannot create new paths. Passing area type in this case is not very useful unless I am missing something.

**Comment by cchenqiang** [comment]
Thank you for your answer.
