### ISSUE TITLE
DynamicNavMesh TileCache.removeObstacle() is protect

### ISSUE THREAD

**Issue by promiselonely** [ppiastucki/recast4j#118]
TileCache.removeObstacle() 
This method is protected，external cannot be accessed

**Comment by ppiastucki** [comment]
Thanks for reporting. The method has been made public.

**Comment by promiselonely** [comment]
can you update it for maven maven repository?thanks☺

**Comment by ppiastucki** [comment]
Done. Version 1.5.2 has been released
