### ISSUE TITLE
Can you please make the DetourCommon methods all public?

### ISSUE THREAD

**Issue by SetoKaiba** [ppiastucki/recast4j#121]
Can you please make the DetourCommon methods all public?
The methods are util methods. It should be useful everwhere.

**Comment by ppiastucki** [comment]
Let me know exactly which methods you want to be made public.
The fewer methods are public the better to limit the burden related to keeping the library backward-compatible.

**Comment by SetoKaiba** [comment]
I see. vDist and vEqual are the two methods now I call them by reflection.
