### ISSUE TITLE
TileCacheBuilder.canRemoveVertex ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hujasonx** [ppiastucki/recast4j#129]
Hi all, thank you for maintaining such a wonderful repo!

I'm trying to make a tiled navmesh; my code follows nearly identically the dungeon example code. However, my game worlds are dynamically generated and I noticed that the more complicated the game world, the more likely it was that this error would be thrown (it sometimes works just fine - and I can confirm that when this error doesn't get thrown, i can visualize a valid navmesh, so I think i have the pipeline set up properly).

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
at org.recast4j.detour.tilecache.TileCacheBuilder.canRemoveVertex(TileCacheBuilder.java:1242)
at org.recast4j.detour.tilecache.TileCacheBuilder.buildTileCachePolyMesh(TileCacheBuilder.java:1612)
at org.recast4j.detour.tilecache.TileCache.buildNavMeshTile(TileCache.java:517)

Is it possible that TileCacheBuilder:1210
`int[] edges = new int[maxEdges];` should be `int[] edges = new int[maxEdges * 3];`?

**Comment by ppiastucki** [comment]
Hi, 
Thanks for reporting the issue. I do not think we need such an estimation at all. I have just create a PR with the related changes and I would be grateful if you could test it.

**Comment by hujasonx** [comment]
Hi Piotr, I patched in your PR and it appears to have resolved the issue. Thanks for the quick response!!
