### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#13]
Hello,

This is merely a feature request.

I have done this in the version I use and am addicted to it. It would be nice to have the methods buildSingleThread and buildMultiThread in the RecastBuilder class have an option to be verbose and println or log estimated time to build RecastBuilderResult in real time. This allows me to  estimate build times so I can do other things. In this example I know I am looking at 32 x 10 sec = aprox 320 seconds build time. 

Something that prints out like this,
32tw x 32th = 1024
Added To Result 1 of 1024: TW 0 TH 0 Time 1043 ms
Added To Result 2 of 1024: TW 0 TH 1 Time 452 ms
[snip]
Returned File Time 12 s
Added To Result 33 of 1024: TW 1 TH 0 Time 332 ms
Added To Result 34 of 1024: TW 1 TH 1 Time 343 ms
[snip]
Returned result Time 10 s
[snip]

On a side note, thank you for your java conversion of recast. Your work is much appreciated.

**Comment by ppiastucki** [comment]
What about something like this https://github.com/ppiastucki/recast4j/commit/a5ddbee2d5cef533c5f609d160dd67b435461593?

**Comment by mitm001** [comment]
That works perfectly. Very nice. Thank you.

**Comment by mitm001** [comment]
Should I close this or will you?
