### ISSUE TITLE
java.io.ioexception invalid magic

### ISSUE THREAD

**Issue by DivyaD2805** [ppiastucki/recast4j#136]
When loading navmesh through .bin file I am getting invalid magic error.
I got the navmesh in tile cache format from unity using navigator.dll.
Any help would be appreciated.

**Comment by ppiastucki** [comment]
I have no idea what navigator.dll is and what kind of files it produces.
You can attach the file to this ticket or check the first 4 bytes in the file i.e. its magic header.

**Comment by ppiastucki** [comment]
No feedback received.
