### ISSUE TITLE
NavMeshDataCreateParams/Recast/RecastConstants   public parameters

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#14]
This could be considered a question or a newbie mistake on my part. 

When using NavMeshDataCreateParams I have to declare these public in order to use them in a non-maven project in Netbeans. Note: I use recast4j as a library.

	public int[] detailMeshes;			///< The height detail sub-mesh data. [Size: 4 * #polyCount]
	public float[] detailVerts;		///< The detail mesh vertices. [Size: 3 * #detailVertsCount] [Unit: wu]
	public int detailVertsCount;		///< The number of vertices in the detail mesh.
	public int[] detailTris;			///< The detail mesh triangles. [Size: 4 * #detailTriCount]
	public int detailTriCount;			///< The number of triangles in the detail mesh.

I personally need access to these variables because I save the parameters to file so I do not have to build the NavMesh from scratch. 

When using Recast, I have to declare this method as public also,

       public static int[] markWalkableTriangles(Context ctx, float walkableSlopeAngle, float[] verts, int[] tris, int nt, AreaModification areaMod) {}

When using RecastConstants, this has to be declared public,

      public static int RC_MESH_NULL_IDX = 0xffff;

If I am making a mistake please let me know.

Robert

**Comment by ppiastucki** [comment]
Thanks for reporting the issues, they are all valid points.

**Comment by akunchen** [comment]
Is there a document can teach me how to use it?
