### ISSUE TITLE
Bug/Useless code for cylinder collision

### ISSUE THREAD

**Issue by AntonioNoack** [ppiastucki/recast4j#144]
In the following code from [org/recast4j/recast/RecastFilledVolumeRasterization.java:243](https://github.com/ppiastucki/recast4j/blob/139addae433ba73aff0519b3230db01e15bf1dd9/recast/src/main/java/org/recast4j/recast/RecastFilledVolumeRasterization.java), the result of the first line is discarded, which makes the call useless, because it has no side-effects.
This probably is a bug.
I'd guess that the results have to be combined, e.g., by mergeIntersections().
```java
private static float[] intersectCylinder(float[] rectangle, float[] start, float[] end, float[] axis, float radiusSqr) {
        float[] s = rayCylinderIntersection(new float[] { clamp(start[0], rectangle[0], rectangle[2]), rectangle[4],
                clamp(start[2], rectangle[1], rectangle[3]) }, start, axis, radiusSqr);
        s = rayCylinderIntersection(new float[] { clamp(end[0], rectangle[0], rectangle[2]), rectangle[4],
                clamp(end[2], rectangle[1], rectangle[3]) }, start, axis, radiusSqr);
```

**Comment by ppiastucki** [comment]
Hi,
Well-spotted. It seems to be a bug indeed. Thanks for reporting.
