### ISSUE TITLE
Typo in the method name PolygonByCircleConstraint.aply()

### ISSUE THREAD

**Issue by capdevon** [ppiastucki/recast4j#150]
Hi guys,
great project! Just wanted to point out a possible typo in the `PolygonByCircleConstraint `interface on the `float[] aply(float[] polyVerts, float[] circleCenter, float radius)` method

By any chance should the method be called `apply` instead of `aply` ?

https://github.com/ppiastucki/recast4j/blob/main/detour/src/main/java/org/recast4j/detour/PolygonByCircleConstraint.java#L25

**Comment by ppiastucki** [comment]
Thanks for reporting. Fixed.
