### ISSUE TITLE
detour.crowd package private

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#16]
A considerable amount of detour.crowd is package private. Is this a transitional step for the package or intended final behavior?

Edit- Explaination: 
I am using recast4j as a library so there is no way to actually keep the detour.crowd package part of it because of everything being package private. Unless I am doing this wrong.

My use is that I have a class that works similar to the AbstractCrowdTest.java in that it creates the Crowd but has its own update loop that ties into the game engines update loop. This is what powers the Crowd by calling the Crowd update loop every frame. 

The Crowd controls all npc movement as its supposed to and I just use the returned npos[] data to move the nodes around that the models are attached to. The node gets the information because I extend the CrowdAgentParams class in a behavior control that gets attached to the node. When the control is attached to the node, it sets all the CrowdAgentParams based off the actual model so all I do is pass the npc node to the Crowd thereafter when it needs to move. Whenever an agent gets added to the crowd I just store its idx in the userData object that CrowdAgentParams offers for future reference.

None of this is possible unless I move the detour.crowd package into the game project and write my classes inside the crowd folder or start changing variables, which will be a mess if I update things from your future releases.

If I am going about using Crowd wrong, please let me know.

**Comment by ppiastucki** [comment]
Definitely all members of CrowdAgentParams and ObstacleAvoidanceParams should be made public. As for other things, the general idea is to expose only the stuff that is really needed. If you find the access modifier too strict in some cases is feel free to submit a PR or an issue with all the details.

BTW, as an interim solution you can create a package named e.g. "detour.crowd" in your project  which will have access to all package private members from the same package in recast4j, you do not need to move any classes from recast4j to this package, just add your stuff here i.e. new classes and overrides.

**Comment by mitm001** [comment]
>  If you find the access modifier too strict in some cases is feel free to submit a PR or an issue with all the details.

I'm still learning what this all does and because of this I may do some things that may not be intended use and could change once I know more. 

For example I currently use CrowdAgent npos[] and targetPos to determine distance from target. I do things like removing the agent from the crowd by calling removeAgent() when they reach the target or when I want to set a new path for them. I set the updateFlags inside a behavior control which gets attached to a node so every NPC that uses that control has the same behavior.

Not sure if that's the way to do things. You have CrowdAgent as package private so I am sure its for a reason and I may be exposing things unnecessarily. 

Have you tried to run this entire project as a library and ran your tests in a separate project?

**Comment by mitm001** [comment]
Sorry for late post, been tied up with wiki work. This is great so far. Just a couple questions.

protected void dumpActiveAgents(int i) of AbstractCrowdTest still has problems because targetState, nvel are package private. Since this is for debug, I guess its a tossup whether or not should change.

setMoveTarget also has problems because of getAgentCount().

Lastly, a question, in CrowdAgentAnimation class the startPos and endPos variables are never set. 

I wanted to make sure the intended use is for me to set these in my code when adding the agent.

**Comment by mitm001** [comment]
After reviewing how requestMoveTargetReplan and requestMoveTarget work, I now know its not possible to use CrowdAgentAnimation  startPos and endPos to store the targetPos when setting the targets,

targetPos has to be public unless I am missing something. The reason I find targetPos important is I do this im my code to update the graphics objects node position,

```
                vCopy(spatialPos, ag.npos);
                vCopy(target, ag.targetPos); 
                Vector2f aiPosition = new Vector2f(spatialPos[0], spatialPos[2]);  
                Vector2f waypoint2D = new Vector2f(target[0], target[2]); 
                float distance = aiPosition.distance(waypoint2D); 
                Vector2f direction = waypoint2D.subtract(aiPosition); 
                if (distance > 1f) {
                    [snip]
               }
```
If I set this in the userData object or store it in CrowdAgentAnimation  when using requestMoveTarget, targetPos can change and I would not know it. Referencing targetPos is the only way to know for sure if its changed so I made it public.

I see nothing in searches that updates the CrowdAgentAnimation startPos and endPos so I am not sure why they are called  [here](https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/Crowd.java#L1081) or if even using targetPos is appropriate for the endPos in CrowdAgentAnimation.

Maybe they get set when using some other pathfinding options or am I missing something.

**Comment by ppiastucki** [comment]
I have made targetRef and targetPos public. Please let me know if there is anything else that should be changed.

**Comment by ppiastucki** [comment]
Can this issue be closed now? Are there any other fields or methods you think should be made public?

**Comment by mitm001** [comment]
Sorry, yes. there are some more but I can deal with them later. This can be closed.
