### ISSUE TITLE
package private2

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#25]
I just updated to 1.0.7 by creating a new library and just adding the maven jars.

Heres whats still package private. 

For dumpActiveAgents in RecastSoloMeshTest: ag.targetState, ag.nvel

In DetourCommon: vDist() method. 

Finally: RecastConstants.RC_CONTOUR_TESS_WALL_EDGES

**Comment by ppiastucki** [comment]
RC_CONTOUR_TESS_WALL_EDGES has been made public, 
targetState should not be visible publicly as it contains internal state.
