### ISSUE TITLE
Comment on Crowd

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#26]
This is not a problem but just some observations. If you know of some settings that change this behavior please let me know.

I have written my own crowd now and added its own getters and setters. I did this because I couldn't figure out how to make Crowd take a straight path from the start position to the next corner in the corridor in a realistic manner. 

Crowd will start the agent in the general direction of the corner and narrow down the distance to the corner each iteration. This leads to weird things when the path moves from an open area to a narrow path like a stair or door. The agent will bounce around the entrance, narrowing the distance to the next corner each iteration so it looks like the agent is searching for a path rather than just moving it to the next corner. calcSmoothSteerDirection() at times will not make sense because of this behavior. The combination of the two will at times lead to the agent making a wide turn when is should of just moved right to the corner it was targeting.

**Comment by ppiastucki** [comment]
I guess you have already played with the flags like: DT_CROWD_ANTICIPATE_TURNS, DT_CROWD_OPTIMIZE_VIS, DT_CROWD_OPTIMIZE_TOPO.

You can find quite a lot of information here: http://digestingduck.blogspot.com.
Some interesting entries:
- http://digestingduck.blogspot.com/2010/11/path-corridor-topology-optimization-in.html
- http://digestingduck.blogspot.com/2010/11/path-corridor-optimizations.html
- http://digestingduck.blogspot.com/2012/05/detour-crowd-path-replanning.html

**Comment by ppiastucki** [comment]
In case you have some ideas for improvements or further questions please discuss them at https://github.com/recastnavigation/recastnavigation/ or https://groups.google.com/forum/#!forum/recastnavigation. I will be happy to port any related changes from C++ to recast4j.
