### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by akunchen** [ppiastucki/recast4j#31]
Is there a document can teach me how to use it? And i don't understand what are the reference id use for?Is build with postion of a dot?

**Comment by ppiastucki** [comment]
The API is kept as close to https://github.com/recastnavigation/recastnavigation as possible so most of the information, hints and examples apply to recast4j too.
You can find a lot of examples in test e.g.
- building a nav mesh from obj files: https://github.com/ppiastucki/recast4j/blob/master/detour/src/test/java/org/recast4j/detour/RecastTestMeshBuilder.java
- finding a path: https://github.com/ppiastucki/recast4j/blob/master/detour/src/test/java/org/recast4j/detour/FindPathTest.java#L94
- persisting a nav mesh: https://github.com/ppiastucki/recast4j/blob/master/detour/src/test/java/org/recast4j/detour/io/MeshSetReaderWriterTest.java
