### ISSUE TITLE
API of Sliced PathFinding

### ISSUE THREAD

**Issue by MeFisto94** [ppiastucki/recast4j#36]
Hey,
this is partially a request for help and maybe some suggestion to redesign the API.
For me, Sliced Pathfinding has two uses:
1. Even the load onto multiple frames
2. Do a Partial Search and re-calculate during the walk

Now I'm having a problem with Point 2 but it's also looking like that in the original Recast Source Code:
It's about this method: http://www.stevefsp.org/projects/rcndoc/prod/classdtNavMeshQuery.html#a01b18dcb5d25fc392b6030ae5d4f310e
In older Versions, finalizeSlicedFindPathPartial was having the "out" parameter `existing`, but that probably was a mistake and `existing` now is an input.

Now how am I supposed to pass `existing` though? In both implementations (the original and recast4j), updateSlicedFindPath doesn't expose the already found polygons, which would've been what one needs. I guess they are only stored in the query, but there is no getter for that either.

I know you want to stay as close to the recast api as possible, so maybe we have to take it upstream (if it's not a misunderstanding on my side).
Also it would be nice to have a test case for this/these two.

**Comment by ppiastucki** [comment]
You can find an example of sliced pathfinding here: https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/Crowd.java#L681.
If the is no existing path and you want to finalize the current search simply call finalizeSlicedFindPath and get the path. finalizeSlicedFindPathPartial returns FindPathResult which contains a newly calculated path too.

**Comment by MeFisto94** [comment]
So finalizeSlicedFindPath works even if the State is still "Running"? Because that's what I'd expect Partial to be like "give me your current state".
But I guess it's just the opposite then? Partial is used to resume the search after I first used FindPath (without Partial)?

btw I've just found a typo in the code you linked:
https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/Crowd.java#L705 that should probably be "ClosesTPoint"...

And good work so far with recast4j, I'll be sure to use it to great extend soon :)

**Comment by ppiastucki** [comment]
The typo should be fixed now. Thanks

**Comment by ppiastucki** [comment]
Is there any additional info I can provide? If not, I would like to close the ticket.

**Comment by MeFisto94** [comment]
Yes I am sorry, I did ask on the Recast Mailing List for clarification, so I found out what sliced pathfinding means to them :)
