### ISSUE TITLE
Can't figure out how to correctly read the mesh information of a PolyMesh and PolyMeshDetail

### ISSUE THREAD

**Issue by TrentWDB** [ppiastucki/recast4j#4]
This is more of a request for help rather than an issue, but I've been trying to read and output the non-triangulated mesh data to an obj.

What I have so far is this:

`for (int i = 0; i < polyMesh.nverts; i++) {
                // not sure this is right
                int xIndex = polyMesh.verts[i * 3];
                int yIndex = polyMesh.verts[i * 3 + 1];
                int zIndex = polyMesh.verts[i * 3 + 2];

                float x = polyMeshDetail.verts[xIndex];
                float y = polyMeshDetail.verts[yIndex];
                float z = polyMeshDetail.verts[zIndex];

                fw.write("v " + x + " " + y + " " + z + "\n");
            }

            for (int i = 0; i < polyMesh.npolys; i++) {
                int polygonIndex = i * 2 * polyMesh.nvp; // following their specs?
                int[] polygon = new int[polyMesh.nvp];

                // fill the polygon with the corresponding part in the polys array
                for (int indexOffset = 0; indexOffset < polyMesh.nvp; indexOffset++) {
                    int polygonVertexIndex = polygonIndex + indexOffset;
                    polygon[indexOffset] = polyMesh.polys[polygonVertexIndex];
                }

                fw.write("f ");
                for (int a = 0; a < polygon.length; a++) {
                    int vertexIndex = polygon[a];
                    if (vertexIndex == 65535) {
                        continue;
                    }

                    fw.write("" + (polygon[a] + 1));
                    if (a < polygon.length - 1) {
                        fw.write(" ");
                    }
                }
                fw.write("\n");
            }`

Any help on this would be appreciated!

Attached is a picture of what the rendered obj looks like. (It at least renders so my code is half correct.)
![screenshot 2016-11-04 04 49 54](https://cloud.githubusercontent.com/assets/5142257/20001443/2bfb2f52-a24a-11e6-9647-ad1d826dc342.png)

**Comment by ppiastucki** [comment]
Hi,
You are mixing PolyMesh and PolyMeshDetail and incorrectly using PolyMesh vertex coordinates (these ints are coordinates, not indices). If you want to save the detail mesh as an obj file you can find a simple example how to do that in RecastSoloMeshTest::saveObj().

**Comment by TrentWDB** [comment]
Finally got it, thanks! I never would have guessed that verts were actually the vertices since it's an int array, but it definitely makes sense given the scale is the cell size!
