### ISSUE TITLE
Difference when generating NavMesh with Recast4j & c++ versions

### ISSUE THREAD

**Issue by Warkdev** [ppiastucki/recast4j#42]
Hello,
I'm trying to understand differences in navmesh creation between c++ and recast4j versions.

When I'm using the same geometry input, the c++ version is creating (and displaying) a navmesh object which is less than 1Mb. Using Recast4j, once I save it:

- I cannot read it with RecastDemo (it's just not loaded)
- The filesize is 29Mb

I'm using the same settings in both cases, so I'm wondering what do I miss in the building process.
Thank you,
Warkdev

**Comment by Warkdev** [comment]
Hello,
Indeed, I do realize that, sorry about it. Here's the code that I'm using:
`InputGeomProvider geometry = new SimpleInputGeomProvider(adt.getShapeMesh().getPoints().toArray(null), indices);

                    RecastConfig cfg = new RecastConfig(RecastConstants.PartitionType.WATERSHED,
                            RecastParameters.getCellSize(), RecastParameters.getCellHeight(), RecastParameters.getWorldUnitWalkableHeight(),
                            RecastParameters.getWalkableRadius(), RecastParameters.getWalkableClimb(), RecastParameters.getWalkableSlopeAngle(),
                            RecastParameters.getMinRegionSize(), RecastParameters.getMergeRegionSize(), RecastParameters.getMaxEdgeLen(),
                            RecastParameters.getMaxSimplificationError(), RecastParameters.getTileVoxelSize(), RecastParameters.getDetailSampleDist(),
                            RecastParameters.getDetailSampleMaxError(), RecastParameters.getTileWidth(), new AreaModification(0x1, 0x07));
                    RecastBuilderConfig bcfg = new RecastBuilderConfig(cfg, geometry.getMeshBoundsMin(), geometry.getMeshBoundsMax());
                    RecastBuilder rcBuilder = new RecastBuilder();
                    int[] twh = Recast.calcTileCount(geometry.getMeshBoundsMin(), geometry.getMeshBoundsMax(), cfg.cs, cfg.tileSize);
                    System.out.println(Arrays.toString(twh));

                    logger.info("Building RC Result.");
                    RecastBuilder.RecastBuilderResult rcResult = rcBuilder.build(geometry, bcfg);
                    logger.info("Build done.");
                    PolyMesh pMesh = rcResult.getMesh();
                    logger.info("Get Mesh done.");
                    for (int i = 0; i < pMesh.npolys; ++i) {
                        pMesh.flags[i] = 1;
                    }
                    PolyMeshDetail dMesh = rcResult.getMeshDetail();
                    logger.info("Get Mesh Details done.");
                    NavMeshDataCreateParams params = new NavMeshDataCreateParams();
                    params.verts = pMesh.verts;
                    params.vertCount = pMesh.nverts;
                    params.polys = pMesh.polys;
                    params.polyAreas = pMesh.areas;
                    params.polyFlags = pMesh.flags;
                    params.polyCount = pMesh.npolys;
                    params.nvp = pMesh.nvp;
                    params.detailMeshes = dMesh.meshes;
                    params.detailVerts = dMesh.verts;
                    params.detailVertsCount = dMesh.nverts;
                    params.detailTris = dMesh.tris;
                    params.detailTriCount = dMesh.ntris;
                    params.walkableHeight = RecastParameters.getWalkableHeight();
                    params.walkableRadius = RecastParameters.getWalkableRadius();
                    params.walkableClimb = RecastParameters.getWalkableClimb();
                    params.bmin = pMesh.bmin;
                    params.bmax = pMesh.bmax;
                    params.cs = RecastParameters.getCellSize();
                    params.ch = RecastParameters.getCellHeight();
                    params.buildBvTree = true;
                    
                    params.offMeshConVerts = new float[0];                    
                    /**params.offMeshConVerts[0] = 0.1f;
                    params.offMeshConVerts[1] = 0.2f;
                    params.offMeshConVerts[2] = 0.3f;
                    params.offMeshConVerts[3] = 0.4f;
                    params.offMeshConVerts[4] = 0.5f;
                    params.offMeshConVerts[5] = 0.6f;*/
                    params.offMeshConRad = new float[0];
                    //params.offMeshConRad[0] = 0.1f;
                    params.offMeshConDir = new int[0];
                    //params.offMeshConDir[0] = 1;
                    params.offMeshConAreas = new int[0];
                    //params.offMeshConAreas[0] = 2;
                    params.offMeshConFlags = new int[0];
                    //params.offMeshConFlags[0] = 12;
                    params.offMeshConUserID = new int[0];
                    //params.offMeshConUserID[0] = 0x4567;
                    params.offMeshConCount = 0;
                    params.tileX = 0;
                    params.tileY = 0;

                    logger.info("Building Nav Mesh MeshData.");
                    meshData = NavMeshBuilder.createNavMeshData(params);   
                    logger.info("Building Done.");                    
                    
                    FileOutputStream fos = new FileOutputStream("D:\\Downloads\\Test\\mesh.mesh");
                    MeshSetWriter writer = new MeshSetWriter();                               
                    logger.info("Creating Nav Mesh.");
                    NavMesh navMesh = new NavMesh(meshData, 6, 0);                                         
                    logger.info("Saving Nav Mesh.");
                    writer.write(fos, navMesh, ByteOrder.BIG_ENDIAN, true);
                    logger.info("NavMesh saved.");
                    fos.close();`

**Comment by ppiastucki** [comment]
And what are RecastParameters?

**Comment by Warkdev** [comment]
As they were similar, I didn't expect them to be relevant, sorry:
`private static final float tileSize = (533f + (1f / 3f));
    private static final int tileVoxelSize = 1800;
    private static final int minRegionSize = 20;
    private static final int mergeRegionSize = 40;

    private static final float cellSize = tileSize / tileVoxelSize;
    private static final float cellHeight = 0.4f;
    private static final float walkableSlopeAngle = 50f;
    private static final float maxSimplificationError = 1.3f;
    private static final float detailSampleDist = 3f;
    private static final float detailSampleMaxError = 1.25f;

    /**
     * Height of wow toon
     */    
    private static final float worldUnitWalkableHeight = 1.652778f;

    /**
     * Maximum height where slope is not considered
     */    
    private static final float worldUnitWalkableClimb = 1.0f;

    /**
     * Radius of wow toon
     */    
    private static final float worldUnitWalkableRadius = 0.2951389f;

    private static final int walkableHeight = (int) Math.round(worldUnitWalkableHeight / cellHeight);
    private static final int walkableClimb = (int) Math.round(worldUnitWalkableClimb / cellHeight);
    private static final int walkableRadius = (int) Math.round(worldUnitWalkableRadius / cellSize);
    private static final int maxEdgeLen = walkableRadius * 8;
    private static final int borderSize = walkableRadius + 4;
    private static final int tileWidth = tileVoxelSize + (borderSize * 2);`

**Comment by ppiastucki** [comment]
Thank you, would you please also include the screenshot of the settings in RecastDemo or c++ code you used to build the nav mesh with c++ version?

**Comment by Warkdev** [comment]
I can't right now but I'm using recastdemo and I'm using the same settings (hopefully). I'm just rounding where I can't enter the exact same value.

**Comment by ppiastucki** [comment]
Ok, but please do so later. I cannot see how you could possibly set tile size to 1800 in RecastDemo for instance as the limits there are set to 16 and 1024.

**Comment by Warkdev** [comment]
That would then explain it! I'm not yet a super user of recast, so please forgive my noobism.

So I guess recastdemo can't display the generated navmesh neither then.

**Comment by Warkdev** [comment]
Indeed, parameters were the root cause of big navmesh. However, I still can't load it in recastdemo. I'm still debugging it right now as I didn't see that some values were calculated in recast config and Im providing already calculated settings.

**Comment by ppiastucki** [comment]
Is there anything else I can help with? If not, I would like to close the issue.

**Comment by Warkdev** [comment]
Hello,
Well, finally I managed to render myself the meshes without using Recastdemo as it seems indeed that my settings couldn't be loaded there.

I'm now trying to understand how recast is managing different terrain type (walkable versus not, terrain versus water, ..). Not related to this issue then.

Thank you so much !

**Comment by ppiastucki** [comment]
I am closing the issue, please create a new one if you spot any further issues. Thanks.
