### ISSUE TITLE
CrowdAgentParams obstacleAvoidanceType typo. <=

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#46]
Erroneous = at end of comment.
https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/CrowdAgentParams.java#L48

https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/Crowd.java#L308

I can pr if want.

Great work Piotr. Thanks for the updates.

**Comment by ppiastucki** [comment]
Well spotted. Probably can be reported upstream too.
