### ISSUE TITLE
How to use titles to finding path?

### ISSUE THREAD

**Issue by cjmxp** [ppiastucki/recast4j#5]
RecastTileMestTest.java:91 line
RecastBuilderResult[][] tiles = builder.buildTiles(geom, cfg, threads);

**Comment by ppiastucki** [comment]
Please see
https://github.com/ppiastucki/recast4j/blob/master/detour/src/test/java/org/recast4j/detour/TiledFindPathTest.java
and
https://github.com/ppiastucki/recast4j/blob/master/detour/src/test/java/org/recast4j/detour/TestTiledNavMeshBuilder.java
