### ISSUE TITLE
PolyMeshDetail offset

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#50]
Not a bug report Piotr, just adding to a comment you made in the code for RecastMeshDetail.

https://github.com/ppiastucki/recast4j/blob/21c494f0d9c9f3b086700078f143cf945166a09b/recast/src/main/java/org/recast4j/recast/RecastMeshDetail.java#L1157

I found this thread about it, wasn't sure if you had seen it.

https://groups.google.com/forum/#!searchin/recastnavigation/detail$20mesh$20offset%7Csort:date/recastnavigation/UQFN6BGCcV0/-1Ny4koOBpkJ

Took us awhile to figure out where this offset was coming from ourselves since we didn't have the intimacy you gained from porting Recast.

**Comment by ppiastucki** [comment]
Thank you very much for the link, I will add it to the comment.
