### ISSUE TITLE
invCellSize of ProximityGrid is not correct

### ISSUE THREAD

**Issue by xiewenqi** [ppiastucki/recast4j#69]
hi, why **invCellSize** of **ProximityGrid** is offerred as constructor arg, instead of calcing using:
`this.m_invCellSize = 1.0f/this.m_cellSize;`
[https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/ProximityGrid.java#L73](url)

There will be serious problem when **Crowd** create **m_grid** using maxAgentRadius * 3 as invCellSize if agent radius is big, which cause ProximityGrid::addItem running into a really heavy time-consuming loop
[https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/Crowd.java#L282](url)
[https://github.com/ppiastucki/recast4j/blob/master/detourcrowd/src/main/java/org/recast4j/detour/crowd/ProximityGrid.java#L96](url)

**Comment by mitm001** [comment]
Your links are broken for some reason. 

https://github.com/ppiastucki/recast4j/blob/9b22492e7cd8fe8237a7529b2c990f0a08151bdd/detourcrowd/src/main/java/org/recast4j/detour/crowd/ProximityGrid.java#L73

https://github.com/ppiastucki/recast4j/blob/9b22492e7cd8fe8237a7529b2c990f0a08151bdd/detourcrowd/src/main/java/org/recast4j/detour/crowd/ProximityGrid.java#L82

https://github.com/ppiastucki/recast4j/blob/9b22492e7cd8fe8237a7529b2c990f0a08151bdd/detourcrowd/src/main/java/org/recast4j/detour/crowd/ProximityGrid.java#L96

Hey Piotr. Here is the recast branch.

https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/DetourCrowd/Source/DetourProximityGrid.cpp#L72

**Comment by ppiastucki** [comment]
Thanks for spotting the issue. I hope it's fixed now.
