### ISSUE TITLE
Overlapping region errors thrown instead of logged

### ISSUE THREAD

**Issue by silentorb** [ppiastucki/recast4j#71]
Recast4j throws an error any time there are overlapping regions.  This prevents completion of the Recast4j process, making it difficult to debug overlapping regions because there is no way to get to data visualization to inspect where overlapping regions are.

In Recast C++ the same code only logs an error.  I changed the same line in Recast4j to a `println`  and the rest of the Recast4j process worked fine even with the overlapping regions.

The C++ version ([RecastRegion.cpp](https://github.com/recastnavigation/recastnavigation/blob/master/Recast/Source/RecastRegion.cpp#L1650)):
```c++
// If overlapping regions were found during merging, split those regions.
if (overlaps.size() > 0)
{
    ctx->log(RC_LOG_ERROR, "rcBuildRegions: %d overlapping regions.", overlaps.size());
}
```

The Recast4j version ([RecastRegion.java](https://github.com/ppiastucki/recast4j/blob/master/recast/src/main/java/org/recast4j/recast/RecastRegion.java#L1449)):
```java
// If overlapping regions were found during merging, split those regions.
if (overlaps.size() > 0) {
    throw new RuntimeException("rcBuildRegions: " + overlaps.size() + " overlapping regions.");
}
```

I would have provided an optional PR but don't know what method of logging would be preferable.  `println` is fine for my needs but not the most universal solution.  I see `logback` is being used in the Recast4j demo module, though it's not in the main modules and its nice that the `recast` and `detour` modules have no external production dependencies.

Maybe there's a better solution than logging?  Maybe returning an error object, C-Style?

**Comment by ppiastucki** [comment]
Thank you very much. Would you mind creating a PR as well? For now, I think we can simply do what is done in other parts and use `ctx.warn()` to log a warning.
