### ISSUE TITLE
InputGeom diff

### ISSUE THREAD

**Issue by mackstone** [ppiastucki/recast4j#9]
Hi..does this project based on the lastest version of recast?I try to build the nav mesh from my obj file,i got this error:

java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at org.recast4j.detour.NavMesh.baseOffMeshLinks(NavMesh.java:920)
	at org.recast4j.detour.NavMesh.addTile(NavMesh.java:460)
	at org.recast4j.detour.NavMesh.<init>(NavMesh.java:255)
	at org.recast4j.detour.DemoTest.createNavMesh(DemoTest.java:30)

I found that the NavMeshDataCreateParams for nav building is different from the native c++ code..

//		params.offMeshConVerts = m_geom->getOffMeshConnectionVerts();
//		params.offMeshConRad = m_geom->getOffMeshConnectionRads();
//		params.offMeshConDir = m_geom->getOffMeshConnectionDirs();
//		params.offMeshConAreas = m_geom->getOffMeshConnectionAreas();
//		params.offMeshConFlags = m_geom->getOffMeshConnectionFlags();
//		params.offMeshConUserID = m_geom->getOffMeshConnectionId();
//		params.offMeshConCount = m_geom->getOffMeshConnectionCount();

The structure of InputGeom Class doest not match the native code..  Maybe i do something wrong??

[Li_Track.zip](https://github.com/ppiastucki/recast4j/files/1049351/Li_Track.zip)

**Comment by ppiastucki** [comment]
I have just committed a fix for this issue. Please re-open if the issue persists,
