### ISSUE TITLE
Agent can not move over off-mesh connection

### ISSUE THREAD

**Issue by weilichuang** [ppiastucki/recast4j#98]
https://github.com/ppiastucki/recast4j/blob/9d71601065b49341420943ba65498390d2e86a21/detourcrowd/src/main/java/org/recast4j/detour/crowd/PathCorridor.java#L238

maybe need add some code like as follow.

https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/DetourCrowd/Source/DetourPathCorridor.cpp#L279

**Comment by ppiastucki** [comment]
Thanks. I have added the missing piece of code. Let me know if it fixes the problem.

**Comment by weilichuang** [comment]
Thanks. it fixed.
